## Pipeline déploiement Gitlab CI pour ListApp
## Application de supervision applicative PHP/Selenium
stages:
  - test
  - save
  - deploy

## Test de syntaxe PHP
test_job:
  stage: test
  script: 
  - 'sudo find . -name \*.php -exec php -l "{}" \;'


## Sauvegarde ancienne version
save_job:
  stage: save
  script:
  - 'sudo rm -rf /var/www/html/dev/listapp_old/'
  - 'sudo cp -rf /var/www/html/dev/listapp/ /var/www/html/dev/listapp_old/'


## Déploiement du nouveau code
deploy_job:
  stage: deploy
  script:
  - 'sudo cd /var/www/html/dev/listapp/ ; sudo git pull ;'
  - 'sudo systemctl reload httpd'
